# Use root/example as user/password credentials
version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    profiles:
      - default

  app:
    build:
      context: docker
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    profiles:
      - app


