app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-ms: 36000000
server:
  port: 8080
#logging:
#    level:
#        root: debug
spring:
  application:
    name: task-master
  devtools:
    restart:
      enabled: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  #                max-page-size: 100
  #                default-page-size: 20
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true
        show_sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
